- name: Check if tailscale is installed
  command: "tailscale --help"
  register: tailscale_check
  ignore_errors: true
- name: Tailscale | Install
  ansible.builtin.shell: "curl -fsSL https://tailscale.com/install.sh | sh"
  when: tailscale_check.rc != 0
- name: Tailscale | Exit node text
  become: true
  copy:
    dest: "/etc/sysctl.d/99-tailscale.conf"
    content: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
  notify: reload sysctl.conf
- name: Tailscale | Exit node Service 
  template: 
    src: tailscale-up.service
    dest: /etc/systemd/system/tailscale-up.service
    chown: root
    owner: root
  when: tailscale_check.rc != 0
  notify:
    - reload systemctl
- name: Tailscale | Funnel Service 
  template: 
    src: tailscale-funnel.service
    dest: /etc/systemd/system/tailscale-funnel.service
    chown: root
    owner: root
  when: tailscale_check.rc != 0
  notify:
  - reload systemctl
